"""Configuration for training YOLO keypoint detection models."""

from pathlib import Path
from dataclasses import dataclass

PROJECT_DIR = Path(__file__).resolve().parents[3]


@dataclass
class TrainingConfig:
    """Configuration class for YOLO keypoint detection model training."""

    # Dataset configuration.
    # Generated by src/data_prep/run_dataload.sh; see data/calibration/README.md.
    dataset_yaml_path: str = PROJECT_DIR / "data" / "calibration" / "unified_output" / "dataset.yaml"

    # Model configuration
    model_name: str = 'yolov11_keypoints_29'
    run: str = 'First'
    start_model_name: str = 'yolov11_keypoints_29'
    start_model_run: str = 'First'

    # Training hyperparameters
    epochs: int = 50
    img_size: int = 640
    batch_size: int = 32
    lr0: float = 0.01
    lrf: float = 0.01
    dropout: float = 0.3

    # Training settings
    resume: bool = True
    save_period: int = 1
    single_cls: bool = True  # A single class covering the pitch
    freeze: bool = False
    seed: int = 44
    plots: bool = True

    # Augmentation settings
    fliplr: float = 0.0
    mosaic: float = 0.3

    # Hardware settings
    device: int = 0

    def __post_init__(self):
        """Resolve the starting weights from start_model_name."""
        if 'original_' in self.start_model_name:
            model_file = f"{self.start_model_name.split('original_')[-1]}.pt"
            self.model_path = PROJECT_DIR / f"runs/{model_file}"
        else:
            self.model_path = PROJECT_DIR / f"runs/{self.start_model_name}/{self.start_model_run}/weights/best.pt"

    @property
    def project_dir(self) -> Path:
        """Directory where the trained models are written."""
        return PROJECT_DIR / f'runs/{self.model_name}'

    def to_dict(self) -> dict:
        """Convert the config into the keyword arguments YOLO training expects."""
        return {
            'data': str(self.dataset_yaml_path),
            'epochs': self.epochs,
            'imgsz': self.img_size,
            'batch': self.batch_size,
            'project': str(self.project_dir),
            'name': self.run,
            'seed': self.seed,
            'resume': self.resume,
            'save': True,
            'save_period': self.save_period,
            'single_cls': self.single_cls,
            'freeze': self.freeze,
            'lr0': self.lr0,
            'lrf': self.lrf,
            'dropout': self.dropout,
            'fliplr': self.fliplr,
            'mosaic': self.mosaic,
            'plots': self.plots,
            'device': self.device,
        }


def get_default_config() -> TrainingConfig:
    """Return the default training configuration."""
    return TrainingConfig()


def create_custom_config(**kwargs) -> TrainingConfig:
    """Create a training configuration with the given overrides applied."""
    config = TrainingConfig()
    for key, value in kwargs.items():
        if hasattr(config, key):
            setattr(config, key, value)
        else:
            raise ValueError(f"Unknown configuration parameter: {key}")

    # Re-run post-init so model_path picks up a changed start_model_name
    config.__post_init__()
    return config
